apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    name: dispatcher-service
spec:
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
    spec:
      containers:
      - name: dispatcher-service
        image: dispatcher-service
        resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
        ports:
        - containerPort: 9003
