apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: catalog-service
spec:
  type: ClusterIP
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9003
